apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
  accessModes:
    # Can be used by a single node at a time
    - ReadWriteOnce
